 # docker image path in artifactory
artifactoryPath: "wdfn"
dockerImageName: "time-series-services"
repoPath: "USGS/time-series-services.git"
gitRepoUrl: "https://github.com/USGS/time-series-services.git"
gitRepoCredentialsId: "Jenkins-GitHub-Read-Write-Token"
deployJobName: "time-series-services-deploy"
projectName: "iow-allgemein"
memory: 512
applicationName: "time-series-services"
# port that is exposed by your container
containerPort: 8080
# string parameter specifying a path that ALB should use to verify that your application is alive
healthCheck: "/api/observations/about/health"
healthCheckIntervalSeconds: 60
configRepoPath: "wma/docker/wdfn/time-series-services"
configCredentialsId: "wma-eto-eb-rsa"
urlRules:
  - type: forward
    conditions:
      - "/api/observations/*"
    priority: 309
tags:
# wma:applicationId, wma:environment, and Name come for free via the ecs deployment pipeline
  wma:costCenter: "TBD"
  wma:organization: "iow"
  wma:contact: "TBD"
  wma:taggingVersion: "0.0.1"
  wma:project_id: "iow"
